config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  get '/auth/:provider/callback', to: 'sessions#create'
  resources :definitions do
  collection do
    get :search
  end
end

  resources :examples
  resources :users

   root 'definitions#index'

end

app/models/definition.rb
class Definition < ActiveRecord::Base
  validates :word, presence: true, uniqueness: true
  validates :meaning, presence: true
  has_many :examples
  accepts_nested_attributes_for :examples
  paginates_per 10
  def self.search(search)
    where("word LIKE ? OR meaning LIKE ?" , "%#{search}%" , "%#{search}%")
  end

  def fancy?
    self.word.length > 16
  end

end

app/models/example.rb
class Example < ActiveRecord::Base
  belongs_to :definition
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:github, :facebook]

         def self.from_omniauth(auth)
             user = where(provider: auth['provider'], uid: auth['uid']).first_or_create

             user.name         = auth.info.name
             user.email        = auth.info.email
             user.nickname     = auth.info.nickname
             user.access_token = auth.credentials.token
             user.password     = Devise.friendly_token[0,20]
             user.save!

             return user
           end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_logged_in
  if current_user.nil?
    redirect_to definitions_path
    return false
  end
end

end

app/controllers/definitions_controller.rb
class DefinitionsController < ApplicationController
  before_filter :ensure_logged_in, only: [:new, :edit, :update, :destroy]
  before_action :set_definition, only: [:show, :edit, :update, :destroy]

  # GET /definitions
  # GET /definitions.json
  def index
    @definitions = Definition.all.page(params[:page])
  end

  def search
    @search = params[:search]
    @definitions = Definition.search(@search).page(params[:page])
    render :index
  end
  # GET /definitions/1
  # GET /definitions/1.json
  def show
  end

  # GET /definitions/new
  def new
    @definition = Definition.new
    @definition.examples.build
  end

  # GET /definitions/1/edit
  def edit
  end

  # POST /definitions
  # POST /definitions.json
  def create
    @definition = Definition.new(definition_params)

    respond_to do |format|
      if @definition.save
        format.html { redirect_to @definition, notice: 'Definition was successfully created.' }
        format.json { render :show, status: :created, location: @definition }
      else
        format.html { render :new }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /definitions/1
  # PATCH/PUT /definitions/1.json
  def update
    respond_to do |format|
      if @definition.update(definition_params)
        format.html { redirect_to @definition, notice: 'Definition was successfully updated.' }
        format.json { render :show, status: :ok, location: @definition }
      else
        format.html { render :edit }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /definitions/1
  # DELETE /definitions/1.json
  def destroy
    @definition.destroy
    respond_to do |format|
      format.html { redirect_to definitions_url, notice: 'Definition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_definition
      @definition = Definition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def definition_params
      params.require(:definition).permit(:word, :meaning, :word_type, examples_attributes: [:id, :example])
    end

end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_filter :ensure_logged_in
  before_action :set_example, only: [:show, :edit, :update, :destroy]
  def show
  end

  def new
    @definition_id = params['definition']
    @example = Example.new
  end

  def create
      @example = Example.new(example_params)

      respond_to do |format|
        if @example.save
          format.html { redirect_to definition_path(id: @example.definition_id), notice: 'Example was successfully created.' }
          format.json { render json: :index, status: :created }
        else
          format.html { render :new }
          format.json { render json: @example.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @example.destroy
      respond_to do |format|
        format.html { redirect_to :back, notice: 'Example was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_example
      @example = Example.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def example_params
      params.require(:example).permit(:example, :definition_id)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Github") if is_navigational_format?
    else
      redirect_to new_user_registration_url
    end
  end
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
end

def new
  @user= User.new
end

def create
  @user = User.create(user_params)
  redirect_to root_path, notice: 'Your account has been created.'
end

  private
  def user_params
    params.permit(:first_name, :last_name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/definitions_helper.rb
module DefinitionsHelper
end

app/helpers/examples_controller_helper.rb
module ExamplesControllerHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/views/definitions/_form.html.erb
<%= form_for(@definition, class: "form-horizontal") do |f| %>
<% if @definition.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@definition.errors.count, "error") %> prohibited this definition from being saved:</h2>

  <ul>
    <% @definition.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :word %><br>
  <%= f.text_field :word %>
</div>
<div class="field">
  <%= f.label :meaning %><br>
  <%= f.text_area :meaning %>
</div>
<%= f.fields_for :examples do |examples_form| %>
<div class="field">
  <%= examples_form.label :example %><br>
  <%= examples_form.text_area :example %>
  <% end %>
</div>
<div class="field">
  <%= f.label :word_type %><br>
  <%= f.select(:word_type, ['verb', 'noun', 'adjective','adverb']) %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/definitions/edit.html.erb
<div class='container'>
<h1>Editing Definition</h1>

<%= render 'form' %>

<%= link_to 'Show', @definition %> |
<%= link_to 'Back', definitions_path %>
</div>

app/views/definitions/index.html.erb
<p id="notice"><%= notice %></p>
<div class='container'>
  <div class="col-md-6">
    <h1 class="row">Definitions</h1>
    <% @definitions.each do |definition| %>
    <div class="row">
      <span>
        <a id='word' href="<%= definition_path(definition) %>" ><%= definition.word %></a>
        <% if user_signed_in? %>
        <%= link_to 'edit word', edit_definition_path(definition) %>
        <%= link_to 'delete word', definition, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'add example', new_example_path(@example, definition: definition.id) %>
        <%end%>
      </span>
    </div>
    <p class="row"><%= definition.word_type %></p>
    <p class="row">
      <%= definition.meaning %>
    </p>
    <p class="row">
      Examples
    </p>
    <% definition.examples.each do |example| %>
    <p>
      <%= example.example %>
        <% if user_signed_in? %>
      <%= link_to '', example, method: :delete, data: { confirm: 'Are you sure?'}, class: "glyphicon glyphicon-fire fire" %>
      <%end%>
    </p>
    <%end%>
    <% end %>
    <%= link_to_previous_page @definitions, 'Previous', params: {search: @search} %>
    <%= link_to_next_page @definitions, 'Next Page', params: {search: @search} %>
  </div>
</div>

app/views/definitions/new.html.erb
<div class='container'>
  <h1>New Definition </h1>

<%= render 'form' %>

</div>

app/views/definitions/show.html.erb
<div class='container'>
  <p id="notice"><%= notice %></p>

  <div class="col-md-6">
    <div class="row">
      <span>
        <span id='word'><%= @definition.word %></span>
        <%= link_to 'Edit', edit_definition_path(@definition) %>
      </span>
    </div>
    <p class="row"><%= @definition.word_type %></p>
    <p class="row">
      <%= @definition.meaning %>
    </p>
    <p class="row">
      Examples
    </p>
    <% @definition.examples.each do |example| %>
    <p>
      <%= example.example %>
      <%= link_to '', example, method: :delete, data: { confirm: 'Are you sure?'}, class: "glyphicon glyphicon-fire fire" %>
    </p>
    <%end%>
    <%= link_to 'Back', definitions_path %>
  </div>

app/views/examples/_form.html.erb
<%= form_for(@example, class: "form-horizontal") do |f| %>
  <% if @example.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@example.errors.count, "error") %> prohibited this example from being saved:</h2>

      <ul>
      <% @example.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.hidden_field :definition_id, value: @definition_id %>
    <%= f.label :example %><br>
    <%= f.text_area :example %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/examples/_nav.html.erb
<div class="navbar navbar-fixed-top navbar_dictionary">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="<%= definitions_path %>"><%= image_tag "icon_rails.png" %></a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <% if current_user != nil %>
            <li id='new_word'><%= link_to 'Add a word', new_definition_path %></li>
          </li>
          <% end %>
        </ul>
        <ul class="nav pull-right">
          <li>
          <form method="get" action="<%= search_definitions_path %>" class="navbar-form pull-right" role="search">
            <input type="text" class="form-control" placeholder="Search" name="search">
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
        </li>
        <% if current_user == nil %>
    <li><%= link_to 'Create an Account', new_user_registration_path %></li>
    <li class="dropdown" id="menuLogin">
      <a class="dropdown-toggle" href="#" data-toggle="dropdown" id="navLogin">Login</a>
      <div class="dropdown-menu" style="padding:17px;">
        <%= form_tag(new_user_session_path, method: :post) %>
        <input name="email" id="email" type="text" placeholder="Email">
        <input name="password" id="password" type="password" placeholder="Password"><br>
        <button class="btn" type="submit">Login</button>
      </form>
    </div>
    <%else%>
    <li><%= link_to "Logout", destroy_user_session_path, method: :delete, data: { confirm: 'Really logout?' } %></li>
    <%end%>
        </ul>
      </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
  </div><!-- /.navbar-inner -->
</div><!-- /.navbar -->

app/views/examples/new.html.erb
<div class='container'>
  <h1>New Example for </h1>

<%= render 'form' %>

</div>

app/views/examples/show.html.erb
<div class='container'>
  <p id="notice"><%= notice %></p>

  <div class="col-md-6">
    <div class="row">
      <span>
        <span id='word'><%= @example.example %></span>
        <%= link_to 'Edit', edit_example_path(@example) %>
      </span>
    </div>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsDictionary</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/nav' %>
<%= yield %>

</body>
</html>

app/views/shared/_nav.html.erb
<div class="navbar navigation">
  <div class="container">
    <a class="navbar-brand logo" href="<%= definitions_path %>"><%= image_tag("icon_rails.png", height:32) %></a>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
        <li id='new_word' class="navigation_link"><%= link_to 'Add a word', new_definition_path %></li>
      </li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav pull-right">
      <li>
        <form method="get" action="<%= search_definitions_path %>" class="navbar-form pull-right" role="search">
          <input type="text" class="form-control" placeholder="Search" name="search">
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
      </li>
      <% if user_signed_in?%>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete, data: { confirm: 'Really logout?' }, class: "navigation_link" %></li>
      <%else%>
      <li><%= link_to 'Create an Account', new_user_registration_path, class: "navigation_link" %></li>
      <li class="dropdown" id="menuLogin">
        <a class="dropdown-toggle navigation_link" href="#" data-toggle="dropdown" id="navLogin">Login</a>
        <div class="dropdown-menu" style="padding:17px;">
          <%= form_tag(new_user_session_path, method: :post) %>
          <input name="email" id="email" type="text" placeholder="Email">
          <input name="password" id="password" type="password" placeholder="Password">
          <div class="login">
          <button class="btn btn-block btn-primary" type="submit">Login</button>
          <%= link_to user_omniauth_authorize_path(:github), class: "btn btn-block btn-social btn-github" do %>
          <i class="fa fa-lg fa-github"></i> Sign in with Github
          <% end %>
          <%= link_to user_omniauth_authorize_path(:facebook), class: "btn btn-block btn-social btn-facebook" do %>
          <i class="fa fa-lg fa-facebook"></i> Sign in with Facebook
          <% end %>
        </div>
        </form>
      </div>

      <%end%>
    </ul>
  </div>
</div>
</div>

app/views/users/_form.html.erb
  <%= form_tag(users_path, method: :post) %>
   <h2 class="form-signin-heading">Create an Account</h2>
   <label for="inputFistName" class="sr-only">Email address</label>
   <input name="first_name" type="text" class="form-control" placeholder="First Name" required autofocus>
   <label for="inputLastName" class="sr-only">Password</label>
   <input name="last_name" type="text" class="form-control" placeholder="Last Name" required>
   <label for="inputEmail" class="sr-only">Email address</label>
   <input name="email" type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
   <label for="inputPassword" class="sr-only">Password</label>
   <input name="password" type="password" id="inputPassword" class="form-control" placeholder="Password" required>
   <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
  </form>

app/views/users/new.html.erb
<div class="container">
<%= render 'form' %>
</div>